In [4]:
import numpy as np
from numpy.linalg import inv, det

from itertools import combinations

def lp_init_bfs(c, G, h):  
    m, n = G.shape
    G_idx = set(range(n))

    B_idxs = list(combinations(G_idx, m))

    N_idxs = []
    for B in B_idxs:
        N_idxs.append(tuple(G_idx - set(B)))

    optimal_idx = -1
    optimal_obj = float("inf")
    
    all_Xs = []
    
    for i, (B_idx, N_idx) in enumerate(zip(B_idxs, N_idxs)):
        i = i + 1
        

        B = G[:, B_idx]
        N = G[:, N_idx]
        print("Possible initial B matrices No.%d" % i)
        print("B index")
        print(B_idx)
        print("N index")
        print(N_idx)
        print("The value of B")
        print(B)
        print("The value of N")
        print(N)
        if det(B) == 0:
            print("B is a singular matrix; No bfs produced")
            continue

        
        Xb = inv(B) @ h
        Xn = np.zeros(n - m)
        print("The value of Xb")
        print(Xb)
        print("The value of Xn")
        print(Xn)
        
        X = np.hstack((Xb, Xn))
        X = X[np.argsort(np.hstack((B_idx, N_idx))), ]
        print("The solution")
        print(X)
        all_Xs.append(X)

        if np.any(X < 0):
            print("Solution does not satisfy non-negativity constraint; No bfs produced")
            continue
        else:
            cX = c @ X
            if cX < optimal_obj:
                optimal_obj = cX
                optimal_idx = i
            print("The objective is %3f" % float(cX))

        print()
    
    print()
    if optimal_idx != -1:
        print("Best initial B's is No.%d w/ objective value %2f" % (optimal_idx, optimal_obj))
    else:
        print("No initial B's has bfs; Check problem")
        
    return all_Xs[optimal_idx], optimal_obj

In [5]:
# Example 5.1
c = np.asarray([-3, 1, -1, 2])

G = np.asarray([
    [1,0,1,2],
    [0,1,1,2]
])
h = np.asarray([2,3])

lp_init_bfs(c, G, h)

Possible initial B matrices No.1
B index
(0, 1)
N index
(2, 3)
The value of B
[[1 0]
 [0 1]]
The value of N
[[1 2]
 [1 2]]
The value of Xb
[2. 3.]
The value of Xn
[0. 0.]
The solution
[2. 3. 0. 0.]
The objective is -3.000000

Possible initial B matrices No.2
B index
(0, 2)
N index
(1, 3)
The value of B
[[1 1]
 [0 1]]
The value of N
[[0 2]
 [1 2]]
The value of Xb
[-1.  3.]
The value of Xn
[0. 0.]
The solution
[-1.  0.  3.  0.]
Solution does not satisfy non-negativity constraint; No bfs produced
Possible initial B matrices No.3
B index
(0, 3)
N index
(1, 2)
The value of B
[[1 2]
 [0 2]]
The value of N
[[0 1]
 [1 1]]
The value of Xb
[-1.   1.5]
The value of Xn
[0. 0.]
The solution
[-1.   0.   0.   1.5]
Solution does not satisfy non-negativity constraint; No bfs produced
Possible initial B matrices No.4
B index
(1, 2)
N index
(0, 3)
The value of B
[[0 1]
 [1 1]]
The value of N
[[1 2]
 [0 2]]
The value of Xb
[1. 2.]
The value of Xn
[0. 0.]
The solution
[0. 1. 2. 0.]
The objective is -1.0000

(array([-1.,  0.,  3.,  0.]), -3.0)

In [6]:
# Exercise 5.1.1
c = np.asarray([-1, 2, 1, -1])
G = np.asarray([
    [1, 3, 2, 0],
    [0, 1, 2, 1],
])
h = np.asarray([5,6])
lp_init_bfs(c, G, h)

Possible initial B matrices No.1
B index
(0, 1)
N index
(2, 3)
The value of B
[[1 3]
 [0 1]]
The value of N
[[2 0]
 [2 1]]
The value of Xb
[-13.   6.]
The value of Xn
[0. 0.]
The solution
[-13.   6.   0.   0.]
Solution does not satisfy non-negativity constraint; No bfs produced
Possible initial B matrices No.2
B index
(0, 2)
N index
(1, 3)
The value of B
[[1 2]
 [0 2]]
The value of N
[[3 0]
 [1 1]]
The value of Xb
[-1.  3.]
The value of Xn
[0. 0.]
The solution
[-1.  0.  3.  0.]
Solution does not satisfy non-negativity constraint; No bfs produced
Possible initial B matrices No.3
B index
(0, 3)
N index
(1, 2)
The value of B
[[1 0]
 [0 1]]
The value of N
[[3 2]
 [1 2]]
The value of Xb
[5. 6.]
The value of Xn
[0. 0.]
The solution
[5. 0. 0. 6.]
The objective is -11.000000

Possible initial B matrices No.4
B index
(1, 2)
N index
(0, 3)
The value of B
[[3 2]
 [1 2]]
The value of N
[[1 0]
 [0 1]]
The value of Xb
[-0.5   3.25]
The value of Xn
[0. 0.]
The solution
[ 0.   -0.5   3.25  0.  ]
Solut

(array([ 0.  , -0.5 ,  3.25,  0.  ]), -11.0)